name: aniview_app
description: A premier Anime, Movies, and Series streaming application.
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
